@startuml
title Add to basket
(*)  --> "Choose Topping and Bottom"
--> "Enter amount"
If "If amount > 0" then
--> [Yes] "Add cupcake to basket"
-->(*)
else
--> [No] "Error message"
"Error message" -right-> Enter amount
Endif

@enduml