@startuml

title "Login - Sequence Diagram"

actor User
boundary index.jsp
boundary customerpage.jsp
participant Login
participant Command
participant FrontController
participant httpServlet
participant UserMapper
database olskercupcakedb

User -> index.jsp : email & password
index.jsp -> Login
Login -> Command: execute()
Command -> FrontController: processRequest()
FrontController -> httpServlet:
httpServlet -> UserMapper:

olskercupcakedb -> UserMapper: resultset
UserMapper -> UserMapper: Validate resultset
UserMapper -> index.jsp: Validate fail
UserMapper -> httpServlet: Validate OK

httpServlet -> customerpage.jsp: forward
customerpage.jsp -> User: Welcome to Olsker's Cupcake

@enduml