@startuml

Title Logging in
State index.jsp
State "Error index.jsp" as error
State LoggedIn

note right of LoggedIn
email and role
stored in session
end note

[*] -> index.jsp
index.jsp --> LoggedIn : user and pw OK
error --> index.jsp : try-again
index.jsp --> error : user or pw not OK
LoggedIn --> [*]

@enduml
